<?php
/**
 * Implementation of hook_menu_alter().
 * Remember to clear the menu cache after adding/editing this function.
 */
function remove_login_tabs_menu_alter(&$items) {
  // Removing user login tabs - note the pages themselves are still available to link to

  // Set these tabs to MENU_CALLBACK, so they still register the path, but just don't show the tab:
	$items['user']['type'] = MENU_CALLBACK;
	$items['user/password']['type'] = MENU_CALLBACK;
	$items['user/register']['type'] = MENU_CALLBACK;

}